### ISSUE TITLE
[BUG] Calculating Stops

### ISSUE THREAD

**Issue by zaphon** [teelolws/TLDRMissions#49] opened 2022-04-20 15:02 UTC
With the latest update I got an error when calculating missions this morning. It did throw an error this time, so I am pasting it below. The mission was Warden's Wrath.

`1x TLDRMissions\simulation.lua:674: attempt to perform arithmetic on field 'shroud' (a nil value)
[string "@TLDRMissions\simulation.lua"]:674: in function `onUnregister'
[string "@TLDRMissions\simulation.lua"]:835: in function <TLDRMissions\simulation.lua:832>
[string "@TLDRMissions\simulation.lua"]:1117: in function <TLDRMissions\simulation.lua:1052>
[string "@TLDRMissions\simulation.lua"]:1454: in function <TLDRMissions\simulation.lua:1422>
[string "@TLDRMissions\simulation.lua"]:1487: in function <TLDRMissions\simulation.lua:1422>
[string "@TLDRMissions\simulation.lua"]:1487: in function <TLDRMissions\simulation.lua:1422>
[string "@TLDRMissions\simulation.lua"]:1465: in function <TLDRMissions\simulation.lua:1422>
[string "@TLDRMissions\simulation.lua"]:1487: in function <TLDRMissions\simulation.lua:1422>
[string "@TLDRMissions\simulation.lua"]:1487: in function <TLDRMissions\simulation.lua:1422>
[string "@TLDRMissions\simulation.lua"]:1465: in function `turnRecursion'
[string "@TLDRMissions\simulation.lua"]:1494: in function <TLDRMissions\simulation.lua:27>
[string "@TLDRMissions\simulation.lua"]:1657: in function `Simulate'
[string "@TLDRMissions\combinations.lua"]:7: in function `func'
[string "@TLDRMissions\workhandler.lua"]:38: in function <TLDRMissions\workhandler.lua:23>

Locals:
(*temporary) = <table> {
 maxHP = 1942
 spells = <table> {
 }
 autoAttack = <table> {
 }
 boardIndex = 2
 name = "Nadjia the Mistblade"
 followerID = "0x00000000206AA9B7"
 baseAttack = 295
 buffs = <table> {
 }
 HP = 629
 thorns = <table> {
 }
}
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on field 'shroud' (a nil value)"
target = <table> {
 maxHP = 1942
 spells = <table> {
 }
 autoAttack = <table> {
 }
 boardIndex = 2
 name = "Nadjia the Mistblade"
 followerID = "0x00000000206AA9B7"
 baseAttack = 295
 buffs = <table> {
 }
 HP = 629
 thorns = <table> {
 }
}
`

**Comment by zaphon** [comment] 2022-04-20 15:05
After skipping the above mission, I got a second error.

`1x TLDRMissions\guihandlers.lua:169: attempt to concatenate local 'itemLink' (a nil value)
[string "@TLDRMissions\guihandlers.lua"]:169: in function <TLDRMissions\guihandlers.lua:131>
[string "@TLDRMissions\combinations.lua"]:356: in function `callback'
[string "@TLDRMissions\combinations.lua"]:19: in function `func'
[string "@TLDRMissions\workhandler.lua"]:38: in function <TLDRMissions\workhandler.lua:23>

Locals:
results = <table> {
 defeats = 0
 missionID = 2333
 combination = <table> {
 }
 incompletes = 0
 victories = 1
}
dontClear = nil
rewards = <table> {
 1 = <table> {
 }
}
text = ""
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = <table> {
 }
}
(for control) = 1
_ = 1
reward = <table> {
 quantity = 1
 itemID = 190178
 itemLink = "|cffffffff|Hitem:190178::::::::60:73::31:::::::|h[]|h|r"
}
_ = nil
itemLink = nil
(*temporary) = ""
(*temporary) = nil
(*temporary) = " x1; "
(*temporary) = "1"
(*temporary) = "; "
(*temporary) = "attempt to concatenate local 'itemLink' (a nil value)"
missionWaitingUserAcceptance = <table> {
 defeats = 0
 missionID = 2333
 combination = <table> {
 }
 incompletes = 0
 victories = 1
}
calculatedMissionBacklog = <table> {
}
alreadyUsedFollowers = <table> {
 -9223372036854775808 = true
 543861230 = true
 543861178 = true
 543860862 = true
 543861175 = true
}
addon = <table> {
 createWorkBatch = <function> defined @TLDRMissions\workhandler.lua:80
 arrangeAllFollowerPositions = <function> defined @TLDRMissions\combinations.lua:28
 reputationCurrencyIDs = <table> {
 }
 updateRewards = <function> defined @TLDRMissions\guihandlers.lua:19
 Simulate = <function> defined @TLDRMissions\simulation.lua:1500
 logSentMission = <function> defined @TLDRMissions\logging.lua:5
 isCurrentWorkBatchEmpty = <function> defined @TLDRMissions\workhandler.lua:98
 unpauseWorker = <function> defined @TLDRMissions\workhandler.lua:72
 GetAllMissions = <function> defined @TLDRMissions\missions.lua:179
 GetAugmentRuneMissions = <function> defined @TLDRMissions\missions.lua:167
 followerXPItemIDs = <table> {
 }
 GetCraftingCacheMissions = <function> defined @TLDRMissions\missions.lua:175
 GetFollowerXPItemMissions = <function> defined @TLDRMissions\missions.lua:155
 arrangeFollowerCombinationsByFewestFollowersPlusTroops = <function> defined @TLDRMissions\combinations.lua:343
 TestExistingMission = <function> defined @TLDRMissions\testing.lua:69
 craftingMaterialsCacheIDs = <table> {
 }
 GetAllMissionsMatchingFilter = <function> defined @TLDRMissions\missions.lua:67
 getCurrentWorkBatchSize = <function> defined @TLDRMissions\workhandler.lua:102
 TestNextCompletedMission = <function> defined @TLDRMissions\testing.lua:4
 clearWork = <function> defined @TLDRMissions\workhandler.lua:91
 GetGoldMissions = <function> defined @TLDRMissions\missions.lua:147
 addWork = <function> defined @TLDRMissions\workhandler.lua:86
 GetAnimaMissions = <function> defined @TLDRMissions\missions.lua:159
 SimulateFromLog = <function> defined @TLDRMissions\simulation.lua:1662
 spellsDB = <table> {
 }
 pauseWorker = <function> defined @TLDRMissions\workhandler.lua:68
 dontWait = false
 GetPetCharmMissions = <function> defined @TLDRMissions\missions.lua:163
 isWorkerPaused = <function> defined @TLDRMissions\workhandler.lua:76
 sortFollowers = <function> defined @TLDRMissions\combinations.lua:130
 TestFirstTenFollowersPlusTroops = <function> defined @TLDRMissions\testing.lua:49
 TestMission = <function> defined @TLDRMissions\testing.lua:78
 GUI = TLDRMissionsFrame {
 }
 logCompletedMission = <function> defined @TLDRMissions\logging.lua:122
 TestGetMissions = <function> defined @TLDRMissions\testing.lua:65
 GetReputationMissions = <function> defined @TLDRMissions\missions.lua:171
 registerWorkStepCallback = <function> defined @TLDRMissions\workhandler.lua:19
 arrangeFollowerCombinationsByMostFollowersPlusTroops = <function> defined @TLDRMissions\combinations.lua:157
 GetFollowerXPMissions = <function> de`

**Comment by teelolws** [comment] 2022-04-20 21:09
First error was caused by a bug with the stealth-handling code. Will be fixed in the next update.

Second error was a byproduct of the first error. Trying to resume calculations when the first errored and stopped.

**Closed by teelolws** 2022-04-20 21:09 UTC
